select * from tb_category;

select * from tb_video;

drop table tb_video;

select * from tb_video;

CREATE TABLE TB_VIDEO
(
    V_ID            SERIAL PRIMARY KEY,
    V_COURSE_ID     INT unique,
    V_DESCRIPTION   VARCHAR(200),
    V_VIDEO_LINK    VARCHAR(200),
    V_DATE_CREATED  TIMESTAMP,
    V_DATE_MODIFIED TIMESTAMP,
    V_USER_CREATED  TIMESTAMP,
    V_USER_MODIFIED TIMESTAMP,
    V_USER_ID       INT,
    CONSTRAINT FK_CO_ID FOREIGN KEY (V_COURSE_ID) REFERENCES TB_COURSE (CO_ID) ON DELETE CASCADE,
);

DROP TABLE TB_VIDEO;
DROP TABLE TB_COURSE;
DROP TABLE TB_COURSE CASCADE;
DROP TABLE TB_USERS;

CREATE TABLE TB_USERS
(
    U_ID            SERIAL PRIMARY KEY,
    U_USERNAME      VARCHAR(100),
    U_PASSWORD      VARCHAR(250),
    U_EMAIL         VARCHAR(100),
    U_PHONE_NUMBER  INT,
    U_DATE_OF_BIRTH TIMESTAMP,
    U_GENDER        VARCHAR(10),
    U_PHOTO         BYTEA,
    U_JOIN_DATE     TIMESTAMP
);



CREATE TABLE TB_COURSE
(
    CO_ID            SERIAL PRIMARY KEY,
    CO_NAME          VARCHAR(100) UNIQUE,
    CO_CATEGORY_NAME VARCHAR(100),
    CO_USER_ID       INT,
    CONSTRAINT FK_CATEGROY FOREIGN KEY (CO_CATEGORY_NAME) REFERENCES TB_CATEGORY (C_NAME) ON DELETE CASCADE ,
    CONSTRAINT FK_USER_ID FOREIGN KEY (CO_USER_ID) REFERENCES TB_USERS (U_ID) ON DELETE CASCADE
);