server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/udemy_project
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Specify the path of the OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs

  # Specify the path of the Swagger UI
  # Enable or disable Swagger UI
  swagger-ui:
    enabled: true
    path: /swagger-ui.html